- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: install dnsmasq config
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq

- name: disable local resolving
  lineinfile:
    path: /etc/default/dnsmasq
    line: DNSMASQ_EXCEPT="lo"
    regexp: '^#DNSMASQ_EXCEPT='
  notify:
    - restart dnsmasq
